### ISSUE TITLE
【悬赏】对原始可执行文件的功能进行测试

### ISSUE THREAD

**Issue by nobodxbodon** [MulanRevive/bounty#4]
之前开始了[初步测试](https://github.com/MulanRevive/bounty/blob/master/%E5%A4%8D%E7%8E%B0%E6%96%87%E6%A1%A3/%E8%AF%AD%E8%A8%80%E8%AE%BE%E8%AE%A1.md)，需要对可执行文件 [ulang-0.2.2.exe](https://github.com/MulanRevive/bounty/blob/master/%E5%8E%9F%E5%A7%8B%E8%B5%84%E6%96%99/%E5%8F%AF%E6%89%A7%E8%A1%8C%E6%96%87%E4%BB%B6/ulang-0.2.2.exe) 进行进一步测试，并形成初步的用户手册，以便更多用户参与补充。

除了基于 python 或 Lua 入门文档尝试逐个功能，另一种门槛较高的方法是根据[源码中的 ply 相关部分](https://github.com/MulanRevive/bounty/issues/1#issuecomment-579524920)针对性地对各个语法规则进行测试。

**Comment by nobodxbodon** [comment]
由于最终必定需要基于 ply 代码验证所有规则，首先学习一下[rply](https://rply.readthedocs.io/en/latest/#user-s-guide)。

第一步，[生成词法分析器](https://rply.readthedocs.io/en/latest/users-guide/lexers.html)。

用于解析简单加减法，只需[下面的代码](https://github.com/program-in-chinese/study/blob/master/%E6%9C%A8%E5%85%B0/rply/%E5%85%A5%E9%97%A8/%E5%88%86%E8%AF%8D/%E6%88%90%E5%8A%9F.py)：
```python
from rply import LexerGenerator

分词器母机 = LexerGenerator()

分词器母机.add('数', r'\d+')

分词器母机.add('加', r'\+')
分词器母机.add('减', r'-')

分词器 = 分词器母机.build()

for 词 in 分词器.lex('1+1-1'):
    print(词)
```
`lg`本为 lexer generator 的缩写，generator 感觉像是机床中[母机](https://baike.baidu.com/item/%E5%B7%A5%E4%BD%9C%E6%AF%8D%E6%9C%BA)的概念。

在 python 3.7.4 下测试：
```
$ python 成功.py 
Token('数', '1')
Token('加', '+')
Token('数', '1')
Token('减', '-')
Token('数', '1')
```

挺好，支持中文词名，如”数/加/减”，很齐整。

接下去，如果[表达式带空格](https://github.com/program-in-chinese/study/blob/master/%E6%9C%A8%E5%85%B0/rply/%E5%85%A5%E9%97%A8/%E5%88%86%E8%AF%8D/%E5%A4%B1%E8%B4%A5.py)，则如预期的分词失败：
```
$ python 失败.py 
Token('数', '1')
Traceback (most recent call last):
  File "失败.py", line 12, in <module>
    for 词 in 分词器.lex('1 + 1'):
  File "/opt/miniconda3/lib/python3.7/site-packages/rply/lexer.py", line 60, in __next__
    return self.next()
  File "/opt/miniconda3/lib/python3.7/site-packages/rply/lexer.py", line 57, in next
    raise LexingError(None, SourcePosition(self.idx, -1, -1))
rply.errors.LexingError: (None, SourcePosition(idx=1, lineno=-1, colno=-1))
```

[忽略空格](https://github.com/program-in-chinese/study/blob/master/%E6%9C%A8%E5%85%B0/rply/%E5%85%A5%E9%97%A8/%E5%88%86%E8%AF%8D/%E5%BF%BD%E7%95%A5%E7%A9%BA%E6%A0%BC.py)后，分词成功：
```
$ python 忽略空格.py 
Token('数', '1')
Token('加', '+')
Token('数', '1')
```

分词入门结束，貌似，简单？

**Comment by nobodxbodon** [comment]
下面，入门[语法分析器生成](https://rply.readthedocs.io/en/latest/users-guide/parsers.html)。

目标是分析简单的四则运算：
```
<表达式> ::= "\d+"
               | <表达式> "+" <表达式>
               | <表达式> "-" <表达式>
               | <表达式> "*" <表达式>
               | <表达式> "/" <表达式>
               | "(" <表达式> ")"
```

如前，先写[分词器]()，发觉文档中此行`lg.ignore('\s+')`的正则表达式少了个 r。

并编写[语法树](https://github.com/program-in-chinese/study/blob/master/%E6%9C%A8%E5%85%B0/rply/%E5%85%A5%E9%97%A8/%E8%AF%AD%E6%B3%95%E5%88%86%E6%9E%90/%E8%AF%AD%E6%B3%95%E6%A0%91%E7%B1%BB.py)，为对应节点编写求值方法。

最后是语法分析器生成。限于 python 水平，直接将分词器、语法树[写在了一起](https://github.com/program-in-chinese/study/blob/c1a53a759a92cc574bd4db4e9796ca7d155e54ed/%E6%9C%A8%E5%85%B0/rply/%E5%85%A5%E9%97%A8/%E8%AF%AD%E6%B3%95%E5%88%86%E6%9E%90/%E8%AF%AD%E6%B3%95%E5%88%86%E6%9E%90%E5%99%A8.py#L54)以便测试。

感觉 rply 对中文标识符的支持很不错，基本上业务相关部分都可以中文化。还有运算符优先级部分尚未摸透，不过可以待看[「木兰」的优先级部分代码](https://github.com/MulanRevive/mulan/blob/31705846e538576c6fbe2754a919a07a86227600/ulang/parser/core.py#L200)时研究：
```python
分析器母机 = ParserGenerator(
    # 所有词名
    ['数', '左括号', '右括号',
     '加', '减', '乘', '除'
    ],
    # A list of precedence rules with ascending precedence, to
    # disambiguate ambiguous production rules.
    precedence=[
        ('left', ['加', '减']),
        ('left', ['乘', '除'])
    ]
)

@分析器母机.production('表达式 : 数')
def 数表达式(片段):
    # 匹配规则右部的片段列表
    return 数(int(片段[0].getstr()))

@分析器母机.production('表达式 : 左括号 表达式 右括号')
def 括号表达式(片段):
    return 片段[1]

@分析器母机.production('表达式 : 表达式 加 表达式')
@分析器母机.production('表达式 : 表达式 减 表达式')
@分析器母机.production('表达式 : 表达式 乘 表达式')
@分析器母机.production('表达式 : 表达式 除 表达式')
def 二元运算表达式(片段):
    左 = 片段[0]
    右 = 片段[2]
    运算符 = 片段[1]
    if 运算符.gettokentype() == '加':
        return 加(左, 右)
    elif 运算符.gettokentype() == '减':
        return 减(左, 右)
    elif 运算符.gettokentype() == '乘':
        return 乘(左, 右)
    elif 运算符.gettokentype() == '除':
        return 除(左, 右)
    else:
        raise AssertionError('不应出现')

分析器 = 分析器母机.build()
```
27 行的规则部分大约花了一小时参透，以此速度对「木兰」的 ply 代码进行分析，最少需要50小时，嗯，可以接受。当然需要更多时间编写测试代码。

**Comment by nobodxbodon** [comment]
之前没有试出木兰while的用法，尝试分析ply代码：
```python
    @pg_.production('while_stmt : WHILE expr block')
    def while_stmt(self, p):
        return ast.While(test=(p[1]),
          body=(p[2]),
          orelse=[],
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))

    @pg_.production('while_stmt : LOOP block')
    def loop_stmt(self, p):
        return ast.While(test=ast.NameConstant(value=True,
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p))),
          body=(p[1]),
          orelse=[],
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))
```

看起来这里有两种循环，一种用`while`可带条件判断，第二种用`loop`没有条件判断。BTW，上面的LOOP的while语法树参数中，不知为何lineno和col_offset出现两次，也许应该清理。

对应分词设置：
```python
lg.add('WHILE', '\\bwhile\\b')
lg.add('LOOP', '\\bloop\\b')
```
于是尝试下面的while测试成功：
```
> sum = 0
> n = 1
> while (n<5) {
>> sum += n
>> n++
>> }
SyntaxError: File "<STDIN>", line 3:2, unexpected token "+"
n++
 ^
> while (n<5) {
>> sum = sum + n
>> n++
>> }
SyntaxError: File "<STDIN>", line 3:2, unexpected token "+"
n++
 ^
> while (n<5) {
>> sum = sum + n
>> n = n+1
>> }
> sum
10
```
顺便发现 n++ 是不允许的。

loop测试如下，用ctrl+c强行中止（下面就要找如何中止循环）：
```
> n=0
> loop {
>> println(n)
>> n=n+1
>> }
0
1
2
3
...
KeyboardInterrupt:
```

break相关ply：
```python
    @pg_.production('break_stmt : BREAK')
    def break_stmt(self, p):
        return ast.Break(lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))
```
分词：
```python
lg.add('BREAK', '\\bbreak\\b')
```


添加了break的loop测试也通过;
```
> n=0
> loop {
>> if (n==5) {
>>   break
>> }
>> n = n+1
>> println(n)
>> }
1
2
3
4
5
```

21行ply代码用时40分钟左右，顺利。接下来可以编写比较完整的用户手册了。顺便总结BNF语法。

**Comment by nobodxbodon** [comment]
因为[之前](https://zhuanlan.zhihu.com/p/103916529)没试出求幂，看到[这里](https://github.com/MulanRevive/mulan/blob/31705846e538576c6fbe2754a919a07a86227600/ulang/parser/core.py#L822)还以为发现第一个 bug 了：
```python
    @pg_.production('bin_expr : expr ^ expr')
...
        elif operator == '**':
            operator = ast.Pow()
```
但试了`5^2`却正确得到 25，需研究如何办到的。

**Comment by nobodxbodon** [comment]
为尽早编写覆盖常用功能的用户手册，尝试从最常用的if开始。表达式有很多种，之后逐渐补全。

<details><summary>if, block声明的ply相关代码</summary>
<p>

```python
    @pg_.production('if_stmt : IF expr block elif_stmt')
    @pg_.production('if_stmt : IF expr block ELSE block')
    @pg_.production('elif_stmt : ')
    @pg_.production('elif_stmt : ELIF expr block elif_stmt')
    @pg_.production('elif_stmt : ELIF expr block ELSE block')
    def if_stmt(self, p):
        if len(p) == 0:
            return []
        elif len(p) == 5:
            return ast.If(test=(p[1]),
              body=(p[2]),
              orelse=(p[(-1)]),
              lineno=(self.getlineno(p)),
              col_offset=(self.getcolno(p)))
        else:
            if not isinstance(p[(-1)], list):
                p[-1] = []

        return ast.If(test=(p[1]),
          body=(p[2]),
          orelse=(p[(-1)]),
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))

    @pg_.production('if_stmt : stmt IF expr')
    def single_if(self, p):
        return ast.If(test=(p[(-1)]),
          body=[
         p[0]],
          orelse=[],
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))
...
    @pg_.production('block : ;')
    @pg_.production('block : LBRACE stmt_list RBRACE')
    def block(self, p):
        if len(p) == 3:
            if p[1]:
                return p[1]
        return [
         ast.Pass(lineno=(self.getlineno(p)),
           col_offset=(self.getcolno(p)))]
```

</p>
</details>

可见if的条件表达式并非一定需要()，而可以是任意表达式。刚发现这和python是一样的，虽然平时看到python的if条件判断都不带()，但的确是可以带的。的确合理，因为这样括号就不再是“特殊的语法”用于表示判断条件，而是与它在表达式中的含义相同。

block必须要{}，或者是单一分号表示空指令。

编写[测试代码](https://github.com/MulanRevive/bounty/commit/f838e486c46e488177c5b168bcdb19f6165811b6)。相信完全未覆盖所有情况，欢迎补充：
- if
- if else
- if elif
- if elif else
- 表达式 if 条件

但其中这部分if相关ply有点特别，尚未参透，待研究：
```python
            if not isinstance(p[(-1)], list):
                p[-1] = []
```

关于[类似python语法设计](https://docs.python.org/3/reference/grammar.html)的bnf，在考虑是否可以通过提取ply的production生成（感觉应该有现成工具可以实现）。
暂时开始[手动编写bnf](https://github.com/MulanRevive/bounty/blob/master/%E5%A4%8D%E7%8E%B0%E6%96%87%E6%A1%A3/%E8%AF%AD%E6%B3%95_en.bnf)。

**Comment by nobodxbodon** [comment]
导入模块是个关键功能，看起来是用`using`：
```python
    @pg_.production('module_name_ : module_name')
    @pg_.production('module_name_ : DOTDOT')
    @pg_.production('module_name_ : DOT')

    @pg_.production('using_stmt : USING module_names IN module_name_')
    @pg_.production('using_stmt : USING * IN module_name_')

    @pg_.production('using_stmt : USING module_names')
```

刚加了`using * in`的[测试](https://github.com/MulanRevive/bounty/commit/9254f80447508c458c2ba379c4a5d91cd9dcf56a)，可以成功导入python模块。

当然也可以[导入木兰自身模块](https://github.com/MulanRevive/bounty/commit/990b3ad3625660b2a6f70ccd793b9d2e2d47dc0b)，模块文件必须用ul结尾，因为[load_ulang_module](https://github.com/MulanRevive/mulan/blob/31705846e538576c6fbe2754a919a07a86227600/ulang/runtime/env.py#L20)用模块名加`.ul`寻找文件。

顺便发现，如果仅仅是运行单个文件，木兰和python同样，都对源代码的扩展名并无要求。比方说`print.mang`文件中有`print(1)`，运行`> python print.mang`照样可以。

【稍后添加其他方式的using测试】

**Comment by nobodxbodon** [comment]
没在parser中找到注释相关内容，看到lexer.py中直接忽略了//后和/**/中间的内容，应该就是注释格式，看起来只支持单行注释。
```python
lg.ignore('//[^\n]*')
lg.ignore('/\\*.*?\\*/', flags=(re.DOTALL))
```
下面打算先编写用户手册第一部分（基本）。

**Comment by nobodxbodon** [comment]
for循环，有几种语法格式可选：
```python
    @pg_.production('for_stmt : FOR iterator IN loop_range block')
    @pg_.production('for_stmt : FOR iterator : loop_range block')

    @pg_.production('for_stmt : stmt FOR iterator IN loop_range')
    @pg_.production('for_stmt : stmt FOR iterator : loop_range')
```
四种语法已[通过测试](https://github.com/MulanRevive/bounty/commit/14d79b9b58a154057823251bb83b6c843fe25f03)。

个人觉得，单语句前置的for语法也许在用途上比较有限，但在真的出现for循环中只有单个语句的情况时，不失为省去大括号的一个办法。

**Comment by nobodxbodon** [comment]
用于生成数列的语法挺直观的：
```python
    @pg_.production('range_expr : expr DOTDOT expr')
    @pg_.production('range_expr : expr DOTDOTLT expr')
    @pg_.production('range_expr : range_expr BY expr')
```

`0..2`, `1..<4`, `-1..4 by 2`已[通过测试](https://github.com/MulanRevive/bounty/commit/ad0278ab116a9db23405c4359f8ea1f442c23c15)。

**Comment by nobodxbodon** [comment]
break，continue与python用法一致：
```python
    @pg_.production('break_stmt : BREAK')
    def break_stmt(self, p):
        return ast.Break(lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))

    @pg_.production('continue_stmt : CONTINUE')
    def continue_stmt(self, p):
        return ast.Continue(lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))
```
[已测试](https://github.com/MulanRevive/bounty/commit/e8603da9bba70aef3b8be83b075bd3eef46371e2)。

**Comment by nobodxbodon** [comment]
函数定义，允许无参数列表，以及指定返回值：

<details><summary>func 声明的ply相关代码</summary>
<p>

```python
    @pg_.production('function : FUNC IDENTIFIER ( param_list ) block')
    @pg_.production('function : FUNC IDENTIFIER block')
    def function(self, p):
        return ast.FunctionDef(name=(p[1].getstr()),
          args=(p[3] if len(p) == 6 else self.param_list()),
          body=(p[(-1)]),
          decorator_list=[],
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))

    @pg_.production('function : FUNC IDENTIFIER ( param_list ) : type_name block')
    @pg_.production('function : FUNC IDENTIFIER : type_name block')
    def function_with_type(self, p):
        return ast.FunctionDef(name=(p[1].getstr()),
          args=(p[3] if len(p) == 8 else self.param_list()),
          body=(p[(-1)]),
          returns=(p[(-2)]),
          decorator_list=[],
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))
。。。

    @pg_.production('type_name : name')
    @pg_.production('type_name : type_name [ type_list ]')
    def type_name(self, p):
        return p[0]

    @pg_.production('type_list : type_name')
    @pg_.production('type_list : type_list , type_name')
    def type_list(self, p):
        if len(p) == 1:
            return [p[0]]
        p[0].append(p[2])
        return p[0]
。。。
    @pg_.production('name : IDENTIFIER')
    def identifier(self, p):
        id = p[0].getstr()
        name = ast.Name(id=id,
          ctx=(ast.Load()),
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))
        if not id.startswith('$'):
            return name
        name.id = 'self'
        return ast.Attribute(value=name,
          attr=(id.replace('$', '')),
          ctx=(ast.Load()),
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))
```

</p>
</details>

留意`IDENTIFIER`如果开头为`$`，有特别语义。待研究。已提交[初步测试用例](https://github.com/MulanRevive/bounty/commit/d1270f6dfe6f9dbcbf647fc32c351914536aed02)，但接着。。。

好家伙，还有类型定义：

<details><summary>类型声明的ply相关代码</summary>
<p>

```python
    @pg_.production('type_define : TYPE name bases type_body')
    def type_define(self, p):
        return ast.ClassDef(name=(p[1].id),
          bases=(p[2]),
          keywords=[],
          body=(p[(-1)]),
          decorator_list=[],
          starargs=None,
          kwargs=None,
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))

    @pg_.production('bases :')
    @pg_.production('bases : : prefix_expr')
    @pg_.production('bases : : prefix_exprs')
    def bases(self, p):
        if len(p) == 0:
            return []
        if isinstance(p[1], list):
            return p[1]
        return [p[1]]

    @pg_.production('type_body : LBRACE type_stmts RBRACE')
    def type_body(self, p):
        return p[1]

    @pg_.production('type_stmts : ')
    @pg_.production('type_stmts : type_stmts type_stmt')
    def type_stmts(self, p):
        if len(p) == 0:
            return []
            if isinstance(p[1], list):
                p[0] += p[1]
        else:
            p[0].append(p[1])
        return p[0]

    @pg_.production('type_stmt : block')
    @pg_.production('type_stmt : type_define')
    @pg_.production('type_stmt : operator')
    @pg_.production('type_stmt : function')
    @pg_.production('type_stmt : property')
    def type_stmt(self, p):
        return p[0]

    @pg_.production('property : ATTR IDENTIFIER block')
    @pg_.production('property : ATTR IDENTIFIER ( ) block')
    @pg_.production('property : ATTR IDENTIFIER = ( param ) block')
    def property(self, p):
        name = p[1].getstr()
        func = ast.FunctionDef(name=name,
          args=(self.param_list()),
          body=(p[(-1)]),
          decorator_list=[],
          lineno=(self.getlineno(p)),
          col_offset=(self.getcolno(p)))
        if len(p) == 7:
            func.args.args.append(p[4])
            func.decorator_list.append(ast.Attribute(value=ast.Name(id=(name.replace('$', '')),
              ctx=(ast.Load()),
              lineno=(self.getlineno(p)),
              col_offset=(self.getcolno(p))),
              attr='setter',
              ctx=(ast.Load()),
              lineno=(self.getlineno(p)),
              col_offset=(self.getcolno(p))))
        else:
            func.decorator_list.append(ast.Name(id='property',
              ctx=(ast.Load()),
              lineno=(self.getlineno(p)),
              col_offset=(self.getcolno(p))))
        return func

```

</p>
</details>

打算先研究类型系统。

**Comment by nobodxbodon** [comment]
原以为可以导入所有[python路径下的模块](https://github.com/MulanRevive/bounty/blob/master/%E6%B5%8B%E8%AF%95%E4%BB%A3%E7%A0%81/%E6%8E%A2%E7%B4%A2/python%E6%A8%A1%E5%9D%97%E5%88%97%E8%A1%A8.md)，但测试过后发现[并不是](https://github.com/MulanRevive/bounty/blob/master/%E6%B5%8B%E8%AF%95%E4%BB%A3%E7%A0%81/%E6%8E%A2%E7%B4%A2/%E5%AF%BC%E5%85%A5%E6%B5%8B%E8%AF%95.md)。

用`__import__`后看到模块有[几种路径](https://github.com/MulanRevive/bounty/blob/master/%E6%B5%8B%E8%AF%95%E4%BB%A3%E7%A0%81/%E6%8E%A2%E7%B4%A2/%E5%AF%BC%E5%85%A5%E8%B7%AF%E5%BE%84%E6%B5%8B%E8%AF%95.md)，但应该都与系统安装的python模块无关。但是，`base_library.zip\\abc.pyc`找得到，但其他非zip下的pyc（如`ast.pyc`）都没在临时文件夹中找到。仍待研究。

另外，在临时文件夹中看到`ulang-MINGW64_NT-10.0-18362-0.2.2.exe.manifest`文件，也许与生成可执行文件的工具链有关。

-----------------------
2.16更新

env.py中有：
```python
    if cwd not in sys.path:
        sys.path.append(cwd)
```
在ulang运行：
```
C:\Users\win7_laptop\Downloads>"ulang-0.2.2.exe"
...
> using sys
> sys.path
[C:\Users\WIN7_L~1\AppData\Local\Temp\_MEI1176802\base_library.zip, C:\Users\WIN
7_L~1\AppData\Local\Temp\_MEI1176802, C:\Users\win7_laptop\Downloads]
```
可以解释最后一项，但不知前两项是何时加的。需研究为何与系统python的sys.path不同。

如果在python的lib目录下运行ulang，可见不少之前无法找到的python模块就可以导入，但是，在目录中的模块比如`tkinter`仍无法导入，可能是功能所限：
```
C:\Users\win7_laptop\AppData\Local\Programs\Python\Python37\Lib>ulang-0.2.2.exe
...
> using turtle
ModuleNotFoundError: No module named '_tkinter'
> using tkinter
ModuleNotFoundError: No module named '_tkinter'
> using aifc
> using antigravity
> using asynchat
> using fractions
```
另外，根据[pyinstaller 文档](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#how-the-one-file-program-works)，之前的临时文件夹`_MEI1176802`中包含了所有依赖的 python 模块，估计 zip 文件也是类似，看来这些库并非当初特意打包。至少有了点头绪，感觉 pyinstaller 的定制选项并非太复杂。打算早日验证对逆向工程进行 pyinstaller 打包。

**Comment by nobodxbodon** [comment]
lambda表达式相关：
```python
    @pg_.production('lambda_param : name')
    @pg_.production('lambda_param : varargs_expr')
    @pg_.production('lambda_param : primary_expr')
    @pg_.production('lambda_param : ( )')

    @pg_.production('lambda_body : -> expr')
    @pg_.production('lambda_body : -> block')

    @pg_.production('lambda_expr : lambda_param lambda_body')
```
提交[初步测试](https://github.com/MulanRevive/bounty/commit/6471e3934d1d69ed261c532af8fbfea4c9163772)。

**Comment by nobodxbodon** [comment]
单行判断
```
    @pg_.production('ternary_expr : expr ? expr : expr')
```
提交[测试](https://github.com/MulanRevive/bounty/commit/b65e84a584afd4f662e18655aed1798d4c8bc1bd)

**Comment by nobodxbodon** [comment]
开始数据结构部分，下面是列表相关ply。
```python
    @pg_.production('list_expr : [ ]')
    @pg_.production('list_expr : [ exprs ]')
```
尚未发现对应[Nested List Comprehensions](https://docs.python.org/3.7/tutorial/datastructures.html#nested-list-comprehensions)和[del](https://docs.python.org/3.7/tutorial/datastructures.html#the-del-statement)的功能。

**Comment by nobodxbodon** [comment]
字典相关：
```python
    @pg_.production('dict_expr : LBRACE : RBRACE')
    @pg_.production('dict_expr : LBRACE kv_pairs RBRACE')
```
判断元素是否存在于字典，不可用`in`（可自定义函数代替），另外，集合好像不支持（可用字典代替）。数据结构[文档](https://github.com/MulanRevive/bounty/blob/master/%E5%A4%8D%E7%8E%B0%E6%96%87%E6%A1%A3/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.md)，尚未编写测试。
